
const invitation = {
  "invitation": {
    "title": "Invitation Management",
    "invitationCode": "Invitation Code",
    "copyCode": "Copy Code",
    "codeStatus": "Status",
    "generator": "Generated By",
    "createDate": "Created Date",
    "validUntil": "Valid Until",
    "usage": "Usage",
    "maxUses": "Maximum Uses",
    "actions": "Actions",
    "generate": "Generate Code",
    "statusActive": "Active",
    "statusInactive": "Inactive",
    "statusExpired": "Expired",
    "noInvitations": "No invitation codes found",
    "filterByStatus": "Filter by Status",
    "searchInvitations": "Search Invitations",
    "generating": "Generating Code...",
    "regenerate": "Regenerate",
    "delete": "Delete",
    "deleteConfirm": "Are you sure you want to delete this invitation code?",
    "statusPending": "Pending",
    "rebateList": "Rebate List",
    "monthlyTarget": "Monthly Target",
    "comparedToLastMonth": "Compared to Last Month",
    "conversionRate": "Conversion Rate",
    "activationRatio": "Activation Ratio",
    
    "rebate": {
      "title": "Rebate Management",
      "total": "Total Rebates",
      "pending": "Pending Approval",
      "completed": "Completed",
      "rejected": "Rejected",
      "amount": "Amount",
      "status": "Status",
      "user": "User",
      "referral": "Referral",
      "date": "Date",
      "note": "Note",
      "filterByStatus": "Filter by Status",
      "searchRebates": "Search Rebates"
    },
    
    "userNames": {
      "user1": "John Smith",
      "user2": "Emily Johnson",
      "user3": "Michael Chen",
      "user4": "Sophia Wang",
      "user5": "Robert Kim",
      "user6": "Isabella Tan"
    },
    
    "stats": {
      "invited": "Invited",
      "activated": "Activated",
      "totalRebate": "Total Rebate"
    },
    
    "rules": {
      "userRegisters": "User Registration",
      "firstDeposit": "First Deposit",
      "transactionRebate1": "Transaction Rebate: ",
      "transactionRebate2": " of total",
      "dailyLimit1": "Daily Limit",
      "dailyLimit2": " points",
      "points": " points"
    },
    
    "rewardRules": "Reward Rules",
    "shareCodeToFriends": "Share code with friends",
    
    "table": {
      "invitee": "Invitee",
      "registerDate": "Register Date",
      "status": "Status",
      "rebateAmount": "Rebate Amount",
      "totalTransaction": "Total Transaction"
    },
    
    "myCode": "My Code",
    "share": "Share",
    "codeCopied": "Code copied",
    "records": "Records",
    "inviteeList": "Invitee List"
  }
};

export default invitation;
