
const invitation = {
  "invitation": {
    "title": "Invitation Management",
    "invitationCode": "Invitation Code",
    "copyCode": "Copy Code",
    "codeStatus": "Status",
    "generator": "Generated By",
    "createDate": "Created Date",
    "validUntil": "Valid Until",
    "usage": "Usage",
    "maxUses": "Maximum Uses",
    "actions": "Actions",
    "generate": "Generate Code",
    "statusActive": "Active",
    "statusInactive": "Inactive",
    "statusExpired": "Expired",
    "noInvitations": "No invitation codes found",
    "filterByStatus": "Filter by Status",
    "searchInvitations": "Search Invitations",
    "generating": "Generating Code...",
    "regenerate": "Regenerate",
    "delete": "Delete",
    "deleteConfirm": "Are you sure you want to delete this invitation code?",
    
    "rebate": {
      "title": "Rebate Management",
      "total": "Total Rebates",
      "pending": "Pending Approval",
      "completed": "Completed",
      "rejected": "Rejected",
      "amount": "Amount",
      "status": "Status",
      "user": "User",
      "referral": "Referral",
      "date": "Date",
      "note": "Note",
      "filterByStatus": "Filter by Status",
      "searchRebates": "Search Rebates"
    },
    
    "userNames": {
      "user1": "John Smith",
      "user2": "Emily Johnson",
      "user3": "Michael Chen",
      "user4": "Sophia Wang",
      "user5": "Robert Kim",
      "user6": "Isabella Tan"
    }
  }
};

export default invitation;
